# Generated by Django 5.0.1 on 2024-01-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Normal')], default=2),
            preserve_default=False,
        ),
    ]
