# Generated by Django 5.0.1 on 2024-01-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (0, 'Normal')], default=2),
        ),
    ]
