# Generated by Django 5.0.1 on 2024-01-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (0, 'Normal')], default=0),
        ),
    ]
