# Generated by Django 4.0.7 on 2024-01-22 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('time_to_send', models.DateTimeField()),
                ('sent', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_tasks', to=settings.AUTH_USER_MODEL)),
                ('precondition_tasks', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_tasks', to='schedule.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
