# Generated by Django 4.0.7 on 2024-01-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='precondition_tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='precondition_tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pre_tasks', to='schedule.task'),
        ),
    ]
