# Generated by Django 3.2.9 on 2021-11-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Normal')]),
        ),
    ]
