# Generated by Django 3.2.9 on 2021-11-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_auto_20211129_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='permissions',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Normal')], null=True),
        ),
    ]
