# Generated by Django 3.2.6 on 2021-08-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='precondition_task',
            field=models.ManyToManyField(blank=True, null=True, to='main.Task'),
        ),
    ]
