# Generated by Django 3.2.6 on 2021-08-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_precondition_task_task_precondition_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='precondition_tasks',
            field=models.ManyToManyField(blank=True, to='main.Task'),
        ),
    ]
