# Generated by Django 3.2.6 on 2021-08-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_task_precondition_tasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-time_to_send']},
        ),
    ]
