# Generated by Django 4.2.8 on 2023-12-06 23:41
from django.contrib.auth.models import Group, Permission
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_name_user_first_name_user_last_name_and_more"),
    ]

    def insert_data(apps, schema_editor):
        # if it has data do not any work
        groups = Group.objects.first()
        if groups:
            return
        # todo: create Group User permissions for users after create task app and add permissions to admin Group

        # add admin group in database
        admin_permissions = Permission.objects.filter(
            codename__in=["add_user", "change_user", "delete_user", "view_user"]
        )
        admin_group = Group.objects.create(
            name="Admin",
        )
        admin_group.save()
        admin_group.permissions.add(*admin_permissions)

        # add user group in database
        user_permissions = []
        user_group = Group.objects.create(
            name="User",
        )
        user_group.save()
        user_group.permissions.add(*user_permissions)

    operations = [
        migrations.RunPython(insert_data)
    ]
