# Generated by Django 4.2.8 on 2023-12-07 00:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_auto_20231207_0311"),
    ]

    operations = []
