# Generated by Django 3.1 on 2021-02-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="time_to_send",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
