# Generated by Django 4.2.8 on 2023-12-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="send_time_done",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="send_time_schedule",
            field=models.DateTimeField(),
        ),
    ]
