# Generated by Django 5.0.1 on 2024-01-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_pre_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pre_tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='task.task'),
        ),
    ]
