# Generated by Django 5.0.1 on 2024-01-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_remove_task_pre_tasks_task_pre_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pre_tasks',
            field=models.ManyToManyField(blank=True, null=True, to='task.task'),
        ),
        migrations.DeleteModel(
            name='PreTask',
        ),
    ]
