# Generated by Django 5.0.1 on 2024-01-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_pre_tasks_delete_pretask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pre_tasks',
            field=models.ManyToManyField(blank=True, to='task.task'),
        ),
    ]
