# Generated by Django 5.0.1 on 2024-01-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_task_pre_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='pre_tasks',
            field=models.ManyToManyField(to='task.task'),
        ),
    ]
