# Generated by Django 5.0.1 on 2024-01-22 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_task_pre_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='pre_tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='pre_tasks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='task.task'),
        ),
    ]
