# Generated by Django 5.0.1 on 2024-01-22 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_father_task_father'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='father',
        ),
        migrations.DeleteModel(
            name='Father',
        ),
    ]
