# Generated by Django 5.0.1 on 2024-01-23 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_remove_task_father_delete_father'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='pre_tasks',
            new_name='pre_task',
        ),
    ]
