# Generated by Django 3.1.6 on 2021-02-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_scheduler', '0003_auto_20210210_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='todo',
            name='content',
            field=models.TextField(default=1),
        ),
    ]
