# Generated by Django 3.1.6 on 2021-02-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_scheduler', '0004_auto_20210210_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='asynce_task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
