# Generated by Django 3.1.6 on 2021-02-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_scheduler', '0005_todo_asynce_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='asynce_task_id',
            new_name='async_task_id',
        ),
    ]
