# Generated by Django 3.2.5 on 2021-08-03 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_tasks_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='description',
            new_name='descriptions',
        ),
    ]
