# Generated by Django 3.2.5 on 2021-08-03 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_description_tasks_descriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='timeToSend',
            new_name='time_to_send',
        ),
    ]
