# Generated by Django 3.1 on 2021-02-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="permissions",
            field=models.CharField(
                choices=[("Normal", "normal"), ("Admin", "admin")],
                default="N",
                max_length=8,
            ),
        ),
    ]
