# Generated by Django 5.0.1 on 2024-02-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tasks', '0002_task_celery_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='celery_job_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
