# Generated by Django 5.0.1 on 2024-02-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tasks', '0003_alter_task_celery_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='celery_job_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
