# Generated by Django 5.0.1 on 2024-02-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tasks', '0004_alter_task_celery_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryJobInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('done', 'Done'), ('pend', 'Pending'), ('failed', 'Failed')], default='pend', max_length=10)),
                ('celery_job_id', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='celery_job_id',
        ),
    ]
