# Generated by Django 5.0.1 on 2024-02-02 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tasks', '0005_celeryjobinfo_remove_task_celery_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeryjobinfo',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_tasks.task'),
        ),
    ]
